import pandas as pd

# Read the first table (Motif - RBP), generated by mCross
motif_rbp = pd.read_csv('motif-RBP.txt', sep='\t', header=None, names=['Motif', 'RBP'])

# Read the second table (Motif - Count)
motif_count = pd.read_csv('DS_exon_motif_results.txt', sep='\t', header=None, names=['Motif', 'Count']) # Or DS_upstream_motif_results.txt, DS_downstream_motif_results.txt
motif_count['Count'] = pd.to_numeric(motif_count['Count'], errors='coerce')

# Merge the two tables to find the corresponding Count for each Motif
merged = pd.merge(motif_rbp, motif_count, on='Motif', how='inner')

# Calculate the total Count for each RBP
rbp_count = merged.groupby('RBP')['Count'].sum().reset_index()

# Output the result
rbp_count.to_csv('DS_RBP_exon_results.txt', sep='\t')   # DS_RBP_upstream_results.txt, DS_RBP_downstream_results.txt
